version: 3

tasks:
  install:
    cmds:
      - pnpm install
      - pnpm prune

  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run build

  outdated:
    desc: Outdated
    aliases: [ dependencyUpdates ]
    deps: [ install ]
    cmds:
      - pnpm outdated

  dev:
    desc: Dev
    deps: [ install ]
    cmds:
      - pnpm run dev

  deploy:
    desc: Deploy to Netlify
    deps: [ build ]
    cmds:
      - netlify deploy --no-build --dir dist